package country

import (
	"github.com/keavon/clout/pkg/resource"
)

// mutiply by 10 to get year rather than per second
const (
	coalIncomeYearly          = resource.CoalReturn * 10
	oilIncomeYearly           = resource.OilReturn * 10
	gasIncomeYearly           = resource.GasReturn * 10
	nuclearIncomeYearly       = resource.NuclearReturn * 10
	geothermalIncomeYearly    = resource.GeothermalReturn * 10
	solarIncomeYearly         = resource.SolarReturn * 10
	windIncomeYearly          = resource.WindReturn * 10
	hydroelectricIncomeYearly = resource.HydroelectricReturn * 10

	coalDamageYearly          = resource.CoalDamage * 10
	oilDamageYearly           = resource.OilDamage * 10
	gasDamageYearly           = resource.GasDamage * 10
	nuclearDamageYearly       = resource.NuclearDamage * 10
	geothermalDamageYearly    = resource.GeothermalDamage * 10
	solarDamageYearly         = resource.SolarDamage * 10
	windDamageYearly          = resource.WindDamage * 10
	hydroelectricDamageYearly = resource.HydroelectricDamage * 10
)

// Countries is a list of all defined countries.
// Note that ID must equal array index
var Countries = []Country{
	Country{
		ID:            0,
		Name:          "United States",
		InitialMoney:  40000000000,
		InitialDemand: 25000000000,
		Coal: ResourceStats{
			Capacity:     100,
			Scalar:       0.75,
			YearlyIncome: coalIncomeYearly,
			YearlyDamage: coalDamageYearly,
		},
		Oil: ResourceStats{
			Capacity:     125,
			Scalar:       0.9,
			YearlyIncome: oilIncomeYearly,
			YearlyDamage: oilDamageYearly,
		},
		Gas: ResourceStats{
			Capacity:     75,
			Scalar:       0.75,
			YearlyIncome: gasIncomeYearly,
			YearlyDamage: gasDamageYearly,
		},
		Nuclear: ResourceStats{
			Capacity:     50,
			Scalar:       0.5,
			YearlyIncome: nuclearIncomeYearly,
			YearlyDamage: nuclearDamageYearly,
		},
		Geothermal: ResourceStats{
			Capacity:     30,
			Scalar:       1,
			YearlyIncome: geothermalIncomeYearly,
			YearlyDamage: geothermalDamageYearly,
		},
		Solar: ResourceStats{
			Capacity:     -1,
			Scalar:       0.9,
			YearlyIncome: solarIncomeYearly,
			YearlyDamage: solarDamageYearly,
		},
		Wind: ResourceStats{
			Capacity:     -1,
			Scalar:       1.25,
			YearlyIncome: windIncomeYearly,
			YearlyDamage: windDamageYearly,
		},
		Hydroelectric: ResourceStats{
			Capacity:     20,
			Scalar:       1,
			YearlyIncome: hydroelectricIncomeYearly,
			YearlyDamage: hydroelectricDamageYearly,
		},
	},
	Country{
		ID:            1,
		Name:          "Japan",
		InitialMoney:  15000000000,
		InitialDemand: 9000000000,
		Coal: ResourceStats{
			Capacity:     50,
			Scalar:       1.5,
			YearlyIncome: coalIncomeYearly,
			YearlyDamage: coalDamageYearly,
		},
		Oil: ResourceStats{
			Capacity:     100,
			Scalar:       1.25,
			YearlyIncome: oilIncomeYearly,
			YearlyDamage: oilDamageYearly,
		},
		Gas: ResourceStats{
			Capacity:     75,
			Scalar:       0.75,
			YearlyIncome: gasIncomeYearly,
			YearlyDamage: gasDamageYearly,
		},
		Nuclear: ResourceStats{
			Capacity:     45,
			Scalar:       0.75,
			YearlyIncome: nuclearIncomeYearly,
			YearlyDamage: nuclearDamageYearly,
		},
		Geothermal: ResourceStats{
			Capacity:     60,
			Scalar:       0.75,
			YearlyIncome: geothermalIncomeYearly,
			YearlyDamage: geothermalDamageYearly,
		},
		Solar: ResourceStats{
			Capacity:     -1,
			Scalar:       2,
			YearlyIncome: solarIncomeYearly,
			YearlyDamage: solarDamageYearly,
		},
		Wind: ResourceStats{
			Capacity:     -1,
			Scalar:       2.5,
			YearlyIncome: windIncomeYearly,
			YearlyDamage: windDamageYearly,
		},
		Hydroelectric: ResourceStats{
			Capacity:     8,
			Scalar:       1,
			YearlyIncome: hydroelectricIncomeYearly,
			YearlyDamage: hydroelectricDamageYearly,
		},
	},
	Country{
		ID:            2,
		Name:          "China",
		InitialMoney:  14000000000,
		InitialDemand: 10000000000,
		Coal: ResourceStats{
			Capacity:     125,
			Scalar:       0.75,
			YearlyIncome: coalIncomeYearly,
			YearlyDamage: coalDamageYearly,
		},
		Oil: ResourceStats{
			Capacity:     125,
			Scalar:       0.9,
			YearlyIncome: oilIncomeYearly,
			YearlyDamage: oilDamageYearly,
		},
		Gas: ResourceStats{
			Capacity:     75,
			Scalar:       0.75,
			YearlyIncome: gasIncomeYearly,
			YearlyDamage: gasDamageYearly,
		},
		Nuclear: ResourceStats{
			Capacity:     5,
			Scalar:       2,
			YearlyIncome: nuclearIncomeYearly,
			YearlyDamage: nuclearDamageYearly,
		},
		Geothermal: ResourceStats{
			Capacity:     10,
			Scalar:       1.5,
			YearlyIncome: geothermalIncomeYearly,
			YearlyDamage: geothermalDamageYearly,
		},
		Solar: ResourceStats{
			Capacity:     -1,
			Scalar:       2,
			YearlyIncome: solarIncomeYearly,
			YearlyDamage: solarDamageYearly,
		},
		Wind: ResourceStats{
			Capacity:     -1,
			Scalar:       0.75,
			YearlyIncome: windIncomeYearly,
			YearlyDamage: windDamageYearly,
		},
		Hydroelectric: ResourceStats{
			Capacity:     150,
			Scalar:       1,
			YearlyIncome: hydroelectricIncomeYearly,
			YearlyDamage: hydroelectricDamageYearly,
		},
	},
	Country{
		ID:            3,
		Name:          "France",
		InitialMoney:  9000000000,
		InitialDemand: 12000000000,
		Coal: ResourceStats{
			Capacity:     100,
			Scalar:       0.75,
			YearlyIncome: coalIncomeYearly,
			YearlyDamage: coalDamageYearly,
		},
		Oil: ResourceStats{
			Capacity:     125,
			Scalar:       0.9,
			YearlyIncome: oilIncomeYearly,
			YearlyDamage: oilDamageYearly,
		},
		Gas: ResourceStats{
			Capacity:     75,
			Scalar:       0.75,
			YearlyIncome: gasIncomeYearly,
			YearlyDamage: gasDamageYearly,
		},
		Nuclear: ResourceStats{
			Capacity:     10,
			Scalar:       1,
			YearlyIncome: nuclearIncomeYearly,
			YearlyDamage: nuclearDamageYearly,
		},
		Geothermal: ResourceStats{
			Capacity:     5,
			Scalar:       2,
			YearlyIncome: geothermalIncomeYearly,
			YearlyDamage: geothermalDamageYearly,
		},
		Solar: ResourceStats{
			Capacity:     -1,
			Scalar:       1.5,
			YearlyIncome: solarIncomeYearly,
			YearlyDamage: solarDamageYearly,
		},
		Wind: ResourceStats{
			Capacity:     -1,
			Scalar:       0.75,
			YearlyIncome: windIncomeYearly,
			YearlyDamage: windDamageYearly,
		},
		Hydroelectric: ResourceStats{
			Capacity:     10,
			Scalar:       1,
			YearlyIncome: hydroelectricIncomeYearly,
			YearlyDamage: hydroelectricDamageYearly,
		},
	},
	Country{
		ID:            4,
		Name:          "United Kingdom",
		InitialMoney:  9000000000,
		InitialDemand: 12000000000,
		Coal: ResourceStats{
			Capacity:     100,
			Scalar:       0.75,
			YearlyIncome: coalIncomeYearly,
			YearlyDamage: coalDamageYearly,
		},
		Oil: ResourceStats{
			Capacity:     125,
			Scalar:       0.9,
			YearlyIncome: oilIncomeYearly,
			YearlyDamage: oilDamageYearly,
		},
		Gas: ResourceStats{
			Capacity:     75,
			Scalar:       0.75,
			YearlyIncome: gasIncomeYearly,
			YearlyDamage: gasDamageYearly,
		},
		Nuclear: ResourceStats{
			Capacity:     15,
			Scalar:       2,
			YearlyIncome: nuclearIncomeYearly,
			YearlyDamage: nuclearDamageYearly,
		},
		Geothermal: ResourceStats{
			Capacity:     3,
			Scalar:       3,
			YearlyIncome: geothermalIncomeYearly,
			YearlyDamage: geothermalDamageYearly,
		},
		Solar: ResourceStats{
			Capacity:     -1,
			Scalar:       1.75,
			YearlyIncome: solarIncomeYearly,
			YearlyDamage: solarDamageYearly,
		},
		Wind: ResourceStats{
			Capacity:     -1,
			Scalar:       0.75,
			YearlyIncome: windIncomeYearly,
			YearlyDamage: windDamageYearly,
		},
		Hydroelectric: ResourceStats{
			Capacity:     20,
			Scalar:       1,
			YearlyIncome: hydroelectricIncomeYearly,
			YearlyDamage: hydroelectricDamageYearly,
		},
	},
	Country{
		ID:            5,
		Name:          "Germany",
		InitialMoney:  8000000000,
		InitialDemand: 12000000000,
		Coal: ResourceStats{
			Capacity:     75,
			Scalar:       1,
			YearlyIncome: coalIncomeYearly,
			YearlyDamage: coalDamageYearly,
		},
		Oil: ResourceStats{
			Capacity:     125,
			Scalar:       0.9,
			YearlyIncome: oilIncomeYearly,
			YearlyDamage: oilDamageYearly,
		},
		Gas: ResourceStats{
			Capacity:     75,
			Scalar:       0.75,
			YearlyIncome: gasIncomeYearly,
			YearlyDamage: gasDamageYearly,
		},
		Nuclear: ResourceStats{
			Capacity:     5,
			Scalar:       1,
			YearlyIncome: nuclearIncomeYearly,
			YearlyDamage: nuclearDamageYearly,
		},
		Geothermal: ResourceStats{
			Capacity:     2,
			Scalar:       3,
			YearlyIncome: geothermalIncomeYearly,
			YearlyDamage: geothermalDamageYearly,
		},
		Solar: ResourceStats{
			Capacity:     -1,
			Scalar:       1.25,
			YearlyIncome: solarIncomeYearly,
			YearlyDamage: solarDamageYearly,
		},
		Wind: ResourceStats{
			Capacity:     -1,
			Scalar:       0.5,
			YearlyIncome: windIncomeYearly,
			YearlyDamage: windDamageYearly,
		},
		Hydroelectric: ResourceStats{
			Capacity:     30,
			Scalar:       1,
			YearlyIncome: hydroelectricIncomeYearly,
			YearlyDamage: hydroelectricDamageYearly,
		},
	},
	Country{
		ID:            6,
		Name:          "Italy",
		InitialMoney:  12000000000,
		InitialDemand: 8000000000,
		Coal: ResourceStats{
			Capacity:     50,
			Scalar:       0.75,
			YearlyIncome: coalIncomeYearly,
			YearlyDamage: coalDamageYearly,
		},
		Oil: ResourceStats{
			Capacity:     75,
			Scalar:       0.9,
			YearlyIncome: oilIncomeYearly,
			YearlyDamage: oilDamageYearly,
		},
		Gas: ResourceStats{
			Capacity:     60,
			Scalar:       0.75,
			YearlyIncome: gasIncomeYearly,
			YearlyDamage: gasDamageYearly,
		},
		Nuclear: ResourceStats{
			Capacity:     5,
			Scalar:       1.5,
			YearlyIncome: nuclearIncomeYearly,
			YearlyDamage: nuclearDamageYearly,
		},
		Geothermal: ResourceStats{
			Capacity:     0,
			Scalar:       1,
			YearlyIncome: geothermalIncomeYearly,
			YearlyDamage: geothermalDamageYearly,
		},
		Solar: ResourceStats{
			Capacity:     -1,
			Scalar:       0.6,
			YearlyIncome: solarIncomeYearly,
			YearlyDamage: solarDamageYearly,
		},
		Wind: ResourceStats{
			Capacity:     -1,
			Scalar:       1.5,
			YearlyIncome: windIncomeYearly,
			YearlyDamage: windDamageYearly,
		},
		Hydroelectric: ResourceStats{
			Capacity:     15,
			Scalar:       1,
			YearlyIncome: hydroelectricIncomeYearly,
			YearlyDamage: hydroelectricDamageYearly,
		},
	},
	Country{
		ID:            7,
		Name:          "Canada",
		InitialMoney:  9000000000,
		InitialDemand: 9000000000,
		Coal: ResourceStats{
			Capacity:     100,
			Scalar:       0.75,
			YearlyIncome: coalIncomeYearly,
			YearlyDamage: coalDamageYearly,
		},
		Oil: ResourceStats{
			Capacity:     155,
			Scalar:       0.9,
			YearlyIncome: oilIncomeYearly,
			YearlyDamage: oilDamageYearly,
		},
		Gas: ResourceStats{
			Capacity:     80,
			Scalar:       0.75,
			YearlyIncome: gasIncomeYearly,
			YearlyDamage: gasDamageYearly,
		},
		Nuclear: ResourceStats{
			Capacity:     20,
			Scalar:       0.5,
			YearlyIncome: nuclearIncomeYearly,
			YearlyDamage: nuclearDamageYearly,
		},
		Geothermal: ResourceStats{
			Capacity:     20,
			Scalar:       1,
			YearlyIncome: geothermalIncomeYearly,
			YearlyDamage: geothermalDamageYearly,
		},
		Solar: ResourceStats{
			Capacity:     -1,
			Scalar:       3,
			YearlyIncome: solarIncomeYearly,
			YearlyDamage: solarDamageYearly,
		},
		Wind: ResourceStats{
			Capacity:     -1,
			Scalar:       0.9,
			YearlyIncome: windIncomeYearly,
			YearlyDamage: windDamageYearly,
		},
		Hydroelectric: ResourceStats{
			Capacity:     20,
			Scalar:       1,
			YearlyIncome: hydroelectricIncomeYearly,
			YearlyDamage: hydroelectricDamageYearly,
		},
	},
	Country{
		ID:            8,
		Name:          "Australia",
		InitialMoney:  9000000000,
		InitialDemand: 9000000000,
		Coal: ResourceStats{
			Capacity:     80,
			Scalar:       0.75,
			YearlyIncome: coalIncomeYearly,
			YearlyDamage: coalDamageYearly,
		},
		Oil: ResourceStats{
			Capacity:     80,
			Scalar:       0.9,
			YearlyIncome: oilIncomeYearly,
			YearlyDamage: oilDamageYearly,
		},
		Gas: ResourceStats{
			Capacity:     70,
			Scalar:       0.75,
			YearlyIncome: gasIncomeYearly,
			YearlyDamage: gasDamageYearly,
		},
		Nuclear: ResourceStats{
			Capacity:     250,
			Scalar:       0.3,
			YearlyIncome: nuclearIncomeYearly,
			YearlyDamage: nuclearDamageYearly,
		},
		Geothermal: ResourceStats{
			Capacity:     0,
			Scalar:       1,
			YearlyIncome: geothermalIncomeYearly,
			YearlyDamage: geothermalDamageYearly,
		},
		Solar: ResourceStats{
			Capacity:     -1,
			Scalar:       0.5,
			YearlyIncome: solarIncomeYearly,
			YearlyDamage: solarDamageYearly,
		},
		Wind: ResourceStats{
			Capacity:     -1,
			Scalar:       0.6,
			YearlyIncome: windIncomeYearly,
			YearlyDamage: windDamageYearly,
		},
		Hydroelectric: ResourceStats{
			Capacity:     25,
			Scalar:       1,
			YearlyIncome: hydroelectricIncomeYearly,
			YearlyDamage: hydroelectricDamageYearly,
		},
	},
	Country{
		ID:            9,
		Name:          "Spain",
		InitialMoney:  8000000000,
		InitialDemand: 7000000000,
		Coal: ResourceStats{
			Capacity:     50,
			Scalar:       0.75,
			YearlyIncome: coalIncomeYearly,
			YearlyDamage: coalDamageYearly,
		},
		Oil: ResourceStats{
			Capacity:     50,
			Scalar:       0.9,
			YearlyIncome: oilIncomeYearly,
			YearlyDamage: oilDamageYearly,
		},
		Gas: ResourceStats{
			Capacity:     50,
			Scalar:       0.75,
			YearlyIncome: gasIncomeYearly,
			YearlyDamage: gasDamageYearly,
		},
		Nuclear: ResourceStats{
			Capacity:     0,
			Scalar:       0.5,
			YearlyIncome: nuclearIncomeYearly,
			YearlyDamage: nuclearDamageYearly,
		},
		Geothermal: ResourceStats{
			Capacity:     0,
			Scalar:       1,
			YearlyIncome: geothermalIncomeYearly,
			YearlyDamage: geothermalDamageYearly,
		},
		Solar: ResourceStats{
			Capacity:     -1,
			Scalar:       0.9,
			YearlyIncome: solarIncomeYearly,
			YearlyDamage: solarDamageYearly,
		},
		Wind: ResourceStats{
			Capacity:     -1,
			Scalar:       1.25,
			YearlyIncome: windIncomeYearly,
			YearlyDamage: windDamageYearly,
		},
		Hydroelectric: ResourceStats{
			Capacity:     12,
			Scalar:       1,
			YearlyIncome: hydroelectricIncomeYearly,
			YearlyDamage: hydroelectricDamageYearly,
		},
	},
	Country{
		ID:            10,
		Name:          "South Korea",
		InitialMoney:  8000000000,
		InitialDemand: 8000000000,
		Coal: ResourceStats{
			Capacity:     30,
			Scalar:       1,
			YearlyIncome: coalIncomeYearly,
			YearlyDamage: coalDamageYearly,
		},
		Oil: ResourceStats{
			Capacity:     40,
			Scalar:       0.9,
			YearlyIncome: oilIncomeYearly,
			YearlyDamage: oilDamageYearly,
		},
		Gas: ResourceStats{
			Capacity:     30,
			Scalar:       0.75,
			YearlyIncome: gasIncomeYearly,
			YearlyDamage: gasDamageYearly,
		},
		Nuclear: ResourceStats{
			Capacity:     5,
			Scalar:       1,
			YearlyIncome: nuclearIncomeYearly,
			YearlyDamage: nuclearDamageYearly,
		},
		Geothermal: ResourceStats{
			Capacity:     25,
			Scalar:       1,
			YearlyIncome: geothermalIncomeYearly,
			YearlyDamage: geothermalDamageYearly,
		},
		Solar: ResourceStats{
			Capacity:     -1,
			Scalar:       1.5,
			YearlyIncome: solarIncomeYearly,
			YearlyDamage: solarDamageYearly,
		},
		Wind: ResourceStats{
			Capacity:     -1,
			Scalar:       0.9,
			YearlyIncome: windIncomeYearly,
			YearlyDamage: windDamageYearly,
		},
		Hydroelectric: ResourceStats{
			Capacity:     20,
			Scalar:       1,
			YearlyIncome: hydroelectricIncomeYearly,
			YearlyDamage: hydroelectricDamageYearly,
		},
	},
	Country{
		ID:            11,
		Name:          "India",
		InitialMoney:  7000000000,
		InitialDemand: 8000000000,
		Coal: ResourceStats{
			Capacity:     100,
			Scalar:       0.75,
			YearlyIncome: coalIncomeYearly,
			YearlyDamage: coalDamageYearly,
		},
		Oil: ResourceStats{
			Capacity:     125,
			Scalar:       0.9,
			YearlyIncome: oilIncomeYearly,
			YearlyDamage: oilDamageYearly,
		},
		Gas: ResourceStats{
			Capacity:     75,
			Scalar:       0.75,
			YearlyIncome: gasIncomeYearly,
			YearlyDamage: gasDamageYearly,
		},
		Nuclear: ResourceStats{
			Capacity:     10,
			Scalar:       0.5,
			YearlyIncome: nuclearIncomeYearly,
			YearlyDamage: nuclearDamageYearly,
		},
		Geothermal: ResourceStats{
			Capacity:     8,
			Scalar:       1,
			YearlyIncome: geothermalIncomeYearly,
			YearlyDamage: geothermalDamageYearly,
		},
		Solar: ResourceStats{
			Capacity:     -1,
			Scalar:       1,
			YearlyIncome: solarIncomeYearly,
			YearlyDamage: solarDamageYearly,
		},
		Wind: ResourceStats{
			Capacity:     -1,
			Scalar:       0.75,
			YearlyIncome: windIncomeYearly,
			YearlyDamage: windDamageYearly,
		},
		Hydroelectric: ResourceStats{
			Capacity:     50,
			Scalar:       1,
			YearlyIncome: hydroelectricIncomeYearly,
			YearlyDamage: hydroelectricDamageYearly,
		},
	},
	Country{
		ID:            12,
		Name:          "Switzerland",
		InitialMoney:  6000000000,
		InitialDemand: 6000000000,
		Coal: ResourceStats{
			Capacity:     30,
			Scalar:       0.75,
			YearlyIncome: coalIncomeYearly,
			YearlyDamage: coalDamageYearly,
		},
		Oil: ResourceStats{
			Capacity:     30,
			Scalar:       0.9,
			YearlyIncome: oilIncomeYearly,
			YearlyDamage: oilDamageYearly,
		},
		Gas: ResourceStats{
			Capacity:     30,
			Scalar:       0.75,
			YearlyIncome: gasIncomeYearly,
			YearlyDamage: gasDamageYearly,
		},
		Nuclear: ResourceStats{
			Capacity:     3,
			Scalar:       0.5,
			YearlyIncome: nuclearIncomeYearly,
			YearlyDamage: nuclearDamageYearly,
		},
		Geothermal: ResourceStats{
			Capacity:     30,
			Scalar:       1,
			YearlyIncome: geothermalIncomeYearly,
			YearlyDamage: geothermalDamageYearly,
		},
		Solar: ResourceStats{
			Capacity:     -1,
			Scalar:       2.5,
			YearlyIncome: solarIncomeYearly,
			YearlyDamage: solarDamageYearly,
		},
		Wind: ResourceStats{
			Capacity:     -1,
			Scalar:       0.4,
			YearlyIncome: windIncomeYearly,
			YearlyDamage: windDamageYearly,
		},
		Hydroelectric: ResourceStats{
			Capacity:     30,
			Scalar:       1,
			YearlyIncome: hydroelectricIncomeYearly,
			YearlyDamage: hydroelectricDamageYearly,
		},
	},
	Country{
		ID:            13,
		Name:          "Taiwan",
		InitialMoney:  6000000000,
		InitialDemand: 5000000000,
		Coal: ResourceStats{
			Capacity:     40,
			Scalar:       0.75,
			YearlyIncome: coalIncomeYearly,
			YearlyDamage: coalDamageYearly,
		},
		Oil: ResourceStats{
			Capacity:     40,
			Scalar:       0.9,
			YearlyIncome: oilIncomeYearly,
			YearlyDamage: oilDamageYearly,
		},
		Gas: ResourceStats{
			Capacity:     40,
			Scalar:       0.75,
			YearlyIncome: gasIncomeYearly,
			YearlyDamage: gasDamageYearly,
		},
		Nuclear: ResourceStats{
			Capacity:     2,
			Scalar:       0.5,
			YearlyIncome: nuclearIncomeYearly,
			YearlyDamage: nuclearDamageYearly,
		},
		Geothermal: ResourceStats{
			Capacity:     20,
			Scalar:       1,
			YearlyIncome: geothermalIncomeYearly,
			YearlyDamage: geothermalDamageYearly,
		},
		Solar: ResourceStats{
			Capacity:     -1,
			Scalar:       1.5,
			YearlyIncome: solarIncomeYearly,
			YearlyDamage: solarDamageYearly,
		},
		Wind: ResourceStats{
			Capacity:     -1,
			Scalar:       0.9,
			YearlyIncome: windIncomeYearly,
			YearlyDamage: windDamageYearly,
		},
		Hydroelectric: ResourceStats{
			Capacity:     15,
			Scalar:       1,
			YearlyIncome: hydroelectricIncomeYearly,
			YearlyDamage: hydroelectricDamageYearly,
		},
	},
	Country{
		ID:            14,
		Name:          "Brazil",
		InitialMoney:  6000000000,
		InitialDemand: 6000000000,
		Coal: ResourceStats{
			Capacity:     80,
			Scalar:       0.75,
			YearlyIncome: coalIncomeYearly,
			YearlyDamage: coalDamageYearly,
		},
		Oil: ResourceStats{
			Capacity:     100,
			Scalar:       0.9,
			YearlyIncome: oilIncomeYearly,
			YearlyDamage: oilDamageYearly,
		},
		Gas: ResourceStats{
			Capacity:     60,
			Scalar:       0.75,
			YearlyIncome: gasIncomeYearly,
			YearlyDamage: gasDamageYearly,
		},
		Nuclear: ResourceStats{
			Capacity:     80,
			Scalar:       0.5,
			YearlyIncome: nuclearIncomeYearly,
			YearlyDamage: nuclearDamageYearly,
		},
		Geothermal: ResourceStats{
			Capacity:     35,
			Scalar:       1,
			YearlyIncome: geothermalIncomeYearly,
			YearlyDamage: geothermalDamageYearly,
		},
		Solar: ResourceStats{
			Capacity:     -1,
			Scalar:       1.25,
			YearlyIncome: solarIncomeYearly,
			YearlyDamage: solarDamageYearly,
		},
		Wind: ResourceStats{
			Capacity:     -1,
			Scalar:       0.75,
			YearlyIncome: windIncomeYearly,
			YearlyDamage: windDamageYearly,
		},
		Hydroelectric: ResourceStats{
			Capacity:     45,
			Scalar:       1,
			YearlyIncome: hydroelectricIncomeYearly,
			YearlyDamage: hydroelectricDamageYearly,
		},
	},
}
